# Generated by Django 4.2.5 on 2023-10-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curso_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('progreso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
                ('cantidad_videos', models.IntegerField()),
                ('autor', models.CharField(max_length=100)),
                ('privacidad', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='lista_reproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.IntegerField()),
                ('id_video', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('rol', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_video', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
    ]
