# Generated by Django 4.2.5 on 2023-10-12 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBDD', '0004_alter_curso_usuario_usercourseid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
