# Generated by Django 4.2.5 on 2023-10-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBDD', '0005_delete_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso_usuario',
            name='UserCourseId',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='CourseId',
        ),
        migrations.RemoveField(
            model_name='lista_reproduccion',
            name='ListId',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='VideoId',
        ),
    ]
