# Generated by Django 4.2.5 on 2023-10-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBDD', '0006_remove_curso_usuario_usercourseid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='videos',
            name='clasificacion',
        ),
    ]
