# Generated by Django 4.2.5 on 2023-10-13 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBDD', '0007_clasificacion_remove_videos_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='tematica',
            field=models.ForeignKey(default='django', on_delete=django.db.models.deletion.PROTECT, to='BBDD.clasificacion', to_field='tema'),
            preserve_default=False,
        ),
    ]
