# Generated by Django 4.2.5 on 2023-10-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBDD', '0011_delete_curso_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='cantidad_videos',
            field=models.IntegerField(default=0),
        ),
    ]
