# Generated by Django 4.2.5 on 2023-10-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBDD', '0012_alter_cursos_cantidad_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='privacidad',
            field=models.BooleanField(default=True),
        ),
    ]
