# Generated by Django 4.2.5 on 2023-10-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBDD', '0014_alter_cursos_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista_central', models.IntegerField(default=-1)),
                ('lista_previa', models.IntegerField(default=-1)),
                ('lista_siguiente', models.IntegerField(default=-1)),
            ],
        ),
    ]
