# Generated by Django 4.2.5 on 2023-11-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBDD', '0015_recomendacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_reproduccion',
            name='posicion',
            field=models.IntegerField(null=True),
        ),
    ]
